development:
  secret_key_base: 

test:
  secret_key_base:


S3_BUCKET_NAME:
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
S3_REGION:
S3_HOST_NAME:



# EXAMPLE: heroku config:set USERNAME=username
#   heroku config
# === glacial-waters-66098 Config Vars
# S3_BUCKET_NAME:           techtimeturing
# AWS_ACCESS_KEY_ID:        AKIAI5ZWYK5WPU6WPBEQ
# AWS_SECRET_ACCESS_KEY:    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
# S3_REGION:               us!!!!!
# S3_HOST_NAME:
# SECRET_KEY_BASE:          1f44d55472b29d97ab98164b2f5e48b9da828e6f841ea98b29256ffe94918fdfd886c47d4bf7bbe349dd8dc564b75314d8e59c7eda45fe12e54a2960f982d8a3
